/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    ResizableHandle: typeof import('./src/components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./src/components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Split: typeof import('./src/components/ui/split/Split.vue')['default']
  }
}
